Style_Tr_App/urls.py
from django.urls import path
from . import views

app_name = 'Style_Tr_App'

urlpatterns = [
    path('transfer/', views.transfer, name='transfer'),
    path('downloadimg/', views.download_img, name='download_img'),
]

Style_Transfer/urls.py
from django.contrib import admin
from django.urls import path, include
from Style_Tr_App import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.show_main_page, name='show_main_page'),
    path('Transfer_Page/', include('Style_Tr_App.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Style_Tr_App/models.py
from django.db import models


class Style_Tr(models.Model): # Так нельзя называть модели, прочитай naming convention
    img_content = models.ImageField(upload_to='images/',
                                    null=True, blank=True)
    img_style = models.ImageField(upload_to='images/',
                                  null=True, blank=True)

    def __str__(self):
        return "Style Transfer Form"

Style_Tr_App/forms.py
from django import forms
from .models import Style_Tr


class ImageForm(forms.ModelForm):
    class Meta:
        model = Style_Tr
        fields = ('img_content', 'img_style')

Style_Tr_App/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Style_Tr
import os
from .forms import ImageForm
from .import Style_Transfer_Modul


def show_main_page(request):
    form = ImageForm()
    return render(request, 'Style_Transfer/Main_Page.html', {'form': form}) #'Style_Transfer/Main_Page.html'много раз дублируется - в константы.


def transfer(request):
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            images = Style_Tr(img_content=request.FILES.get('img_content'),
                              img_style=request.FILES.get('img_style'))
            form.save()
            Style_Transfer_Modul.transfer_function(images.img_content.path,
                                                   images.img_content.path, 10)
            return render(request, 'Style_Transfer/Main_Page.html', {'form': form})
    else:
        form = ImageForm()
    return render(request, 'Style_Transfer/Main_Page.html', {'form': form})# возвращаешь одно и то же, можно сделать это 1 раз в конце функции.


def download_img(request):
    file_path = './media/images/stylized-image.png'
    file = open(file_path, 'rb')
    response = HttpResponse(file.read(), content_type='Image')
    response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
    return response

Style_Transfer/templates/Style_Transfer/Main_Page.html
{% extends 'base.html' %}

{% block titel%}Neural Style Transfer{% endblock %}


{% block content %}
    <div class="header">
        <h2>[ ] Neural Style Transfer</h2>
    </div>
    <div class="example_">
        <img src="../../../media/images/stylized-image.png" alt="connect" >
    </div>
<div class="style_transfer_form">

    <form action="{% url 'Style_Tr_App:transfer' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
       {{ form.as_p }}

      <button type="submit">Upload</button>
    </form>
</div>
    <div class = 'download_button'>
        <a href="{% url 'Style_Tr_App:download_img' %}" >Download</a>
    </div>
<div class = 'text_content'>
    <p><strong>Neural Style Transfer (NST)</strong> refers to a class of software
    algorithms that manipulate digital images, or videos, in order to adopt the
    appearance or visual style of another image. NST algorithms are characterized by their
    use of deep neural networks for the sake of image transformation. Common uses for NST are
    the creation of artificial artwork from photographs, for example by transferring
    the appearance of famous paintings to user-supplied photographs.</p>
</div>
{% endblock %}

Style_Transfer/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titel%} Titel blyt {% endblock %}</title>
{% block link_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}
</head>
{% block body_color %}
    <body>
        {% block content%} Content blyt {% endblock %}
    </body>
{% endblock %}
</html>